serif: true # use a serif font (Lora) instead of sans-serif (Open Sans)

title: "EthanMcBloxxer" # title of blog or your name
subtitle: "Creator of Writeas.Jekyll" # subtitle of blog or your position / minbio
links:
  about: /about/
  contact: mailto:ethanmcbloxxer@pm.me
  rss: /feed.xml
permalink: /:title/
credit: true # show a footer "published with jekyll-theme-writeas" (only on posts)

#background: "#202325"
#text: "#dadad9"
#accent: "#dadad9"
#link: "#139ee0"
#code: "#cccccc"

paginate: 10 # how many posts on a page
paginate_path: "/page/:num/" # page 2 would be served at /page/2/
older_text: false # text to be displayed for older posts nav
newer_text: false # text to be displayed for newer posts nav

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
